name: Push-to-EC2

# Trigger only for push to master branch
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to EC2 when push happens to master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.DIRECTORY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          echo setting up ssh
          ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} "
            cd ${TARGET}/.. &&
            sudo rm -rf ${TARGET} &&
            git clone git@github.com:6156Project/PlaylistPro-Users.git &&
            cd ${TARGET} &&
            pkill -9 python &&
            python3 -m pip install -r requirements.txt &&
            cd ./src &&
            source env.sh &&
            nohup python3 -m application"
          echo "done with work..."